version: '3'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    container_name: app_web
    command: yarn start
    restart: unless-stopped
    environment:
      - APP_WEB_HOST=0.0.0.0
      - APP_WEB_PORT=3000
      - APP_WEB_API_HOST=http://api:4554
    ports:
      - "3000:3000"
    networks:
      - app_platform

  api:
    build: ./api
    container_name: app_api
    command: yarn start
    restart: unless-stopped
    environment:
      - PORT=4554
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
    networks:
      - app_platform

  api_db:
    image: mongo:latest
    container_name: app_api_db
    volumes:
      - mongodb_api:/data/db
    networks:
      - app_platform

  nginx:
    image: nginx:stable-alpine
    container_name: app_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - web
      - api
    networks:
      - app_platform

volumes:
  mongodb_api:

networks:
  app_platform:
    driver: bridge
